# Generated by Django 4.0.3 on 2022-04-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_review'),
        ('reviews', '0002_rename_review_number_review_number_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
