# Generated by Django 4.0.3 on 2022-04-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
