# Generated by Django 4.0.3 on 2022-04-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_review',
        ),
    ]
